require("bcummings.plugins-setup")
require("bcummings.core.options")
require("bcummings.core.keymaps")
require("bcummings.core.colorscheme")
require("bcummings.plugins.nvim-tree")
require("bcummings.plugins.nvim-cmp")
require("bcummings.plugins.lsp.mason")
require("bcummings.plugins.lsp.lspsaga")
require("bcummings.plugins.lsp.lspconfig")
require("bcummings.plugins.lsp.null-ls")
require("bcummings.plugins.autopairs")
--require("bcummings.plugins.treesitter")

