require("bcummings.plugins-setup")
require("bcummings.core.options")
require("bcummings.core.keymaps")
require("bcummings.core.colorscheme")
require("bcummings.plugins.nvim-tree")
--require("bcummings.plugins.treesitter")
